version: '3.8'

services:
  web:
    image: kryonix-plataforma:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 10s
      labels:
        # Traefik básico
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-public"

        # Configuração do serviço web
        - "traefik.http.services.kryonix-web.loadbalancer.server.port=8080"

        # WEBHOOK - PRIORIDADE MÁXIMA (10000)
        - "traefik.http.routers.kryonix-webhook.rule=Host(`kryonix.com.br`) && Path(`/api/github-webhook`)"
        - "traefik.http.routers.kryonix-webhook.entrypoints=web,websecure"
        - "traefik.http.routers.kryonix-webhook.service=kryonix-web"
        - "traefik.http.routers.kryonix-webhook.priority=10000"
        - "traefik.http.routers.kryonix-webhook.tls=true"
        - "traefik.http.routers.kryonix-webhook.tls.certresolver=letsencryptresolver"

        # API Routes - Alta Prioridade (9000)
        - "traefik.http.routers.kryonix-api.rule=Host(`kryonix.com.br`) && PathPrefix(`/api/`)"
        - "traefik.http.routers.kryonix-api.entrypoints=web,websecure"
        - "traefik.http.routers.kryonix-api.service=kryonix-web"
        - "traefik.http.routers.kryonix-api.priority=9000"
        - "traefik.http.routers.kryonix-api.tls=true"
        - "traefik.http.routers.kryonix-api.tls.certresolver=letsencryptresolver"

        # HTTPS Principal - Prioridade Normal (100)
        - "traefik.http.routers.kryonix-https.rule=Host(`kryonix.com.br`) || Host(`www.kryonix.com.br`)"
        - "traefik.http.routers.kryonix-https.entrypoints=websecure"
        - "traefik.http.routers.kryonix-https.service=kryonix-web"
        - "traefik.http.routers.kryonix-https.priority=100"
        - "traefik.http.routers.kryonix-https.tls=true"
        - "traefik.http.routers.kryonix-https.tls.certresolver=letsencryptresolver"

        # HTTP - Redirecionamento (50)
        - "traefik.http.routers.kryonix-http.rule=Host(`kryonix.com.br`) || Host(`www.kryonix.com.br`)"
        - "traefik.http.routers.kryonix-http.entrypoints=web"
        - "traefik.http.routers.kryonix-http.service=kryonix-web"
        - "traefik.http.routers.kryonix-http.priority=50"
        - "traefik.http.routers.kryonix-http.middlewares=https-redirect"

        # Middleware HTTPS Redirect
        - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
        - "traefik.http.middlewares.https-redirect.redirectscheme.permanent=true"

        # Middleware de Segurança para API
        - "traefik.http.middlewares.api-security.headers.customrequestheaders.X-Forwarded-Proto=https"
        - "traefik.http.middlewares.api-security.headers.customresponseheaders.X-Frame-Options=SAMEORIGIN"
        - "traefik.http.routers.kryonix-webhook.middlewares=api-security"
        - "traefik.http.routers.kryonix-api.middlewares=api-security"

    networks:
      - traefik-public
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
      - AUTO_UPDATE_DEPS=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  webhook:
    image: kryonix-plataforma:latest
    command: ["node", "webhook-listener.js"]
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 10s
    networks:
      - traefik-public
    ports:
      - "8082:8082"
    environment:
      - NODE_ENV=production
      - PORT=8082
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  monitor:
    image: kryonix-plataforma:latest
    command: ["node", "kryonix-monitor.js"]
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 10s
    networks:
      - traefik-public
    ports:
      - "8084:8084"
    environment:
      - NODE_ENV=production
      - PORT=8084
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8084/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  traefik-public:
    external: true
