services:
  - type: web
    name: kryonix-backend
    runtime: node
    plan: starter
    region: oregon
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: JWT_SECRET
        generateValue: true
      - key: WEBHOOK_SECRET
        generateValue: true
    autoDeploy: true
    repo: https://github.com/vitorfernandes-kryonix/kryonix-plataforma
    branch: main
    rootDir: ./
    
  - type: postgres
    name: kryonix-database
    plan: starter
    databaseName: kryonix_production
    user: kryonix_admin
    region: oregon
    
databases:
  - name: kryonix-database
    databaseName: kryonix_production
    user: kryonix_admin

# Environment Variables Template for Render
# Set these in your Render dashboard:
#
# Required:
# - DATABASE_URL (automatically set by Render for PostgreSQL)
# - JWT_SECRET (generate a secure random string)
# - WEBHOOK_SECRET (generate a secure random string)
#
# Optional:
# - FRONTEND_URL=https://kryonix-plataforma.vercel.app
# - CORS_ORIGIN=https://kryonix-plataforma.vercel.app,https://www.kryonix.com.br
# - LOG_LEVEL=info
# - RATE_LIMIT_WINDOW_MS=900000
# - RATE_LIMIT_MAX_REQUESTS=100
