services:
  - type: web
    name: kryonix-backend
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm ci && npm run build-fast
    startCommand: npm run production
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: HOSTNAME
        value: 0.0.0.0
      - key: JWT_SECRET
        generateValue: true
      - key: WEBHOOK_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://kryonix-platform.vercel.app
      - key: DATABASE_URL
        sync: false  # Configure manually with Neon Database URL
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
      - key: NODE_OPTIONS
        value: "--max-old-space-size=1024"
    disk:
      name: kryonix-data
      mountPath: /app/data
      sizeGB: 1
