#!/bin/bash

# Script para criar todas as 50 pastas dos tutoriais KRYONIX
# Foco: Configurações externas das stacks já instaladas no Docker Swarm

mkdir -p "parte-01-configuracao-keycloak-autenticacao"
mkdir -p "parte-02-configuracao-postgresql-database"
mkdir -p "parte-03-configuracao-minio-storage"
mkdir -p "parte-04-configuracao-redis-cache"
mkdir -p "parte-05-configuracao-traefik-proxy"
mkdir -p "parte-06-configuracao-grafana-prometheus-monitor"
mkdir -p "parte-07-configuracao-rabbitmq-mensageria"
mkdir -p "parte-08-configuracao-backup-automatico"
mkdir -p "parte-09-configuracao-seguranca-basica"
mkdir -p "parte-10-configuracao-api-gateway"
mkdir -p "parte-11-interface-principal-frontend"
mkdir -p "parte-12-dashboard-administrativo"
mkdir -p "parte-13-sistema-usuarios-perfis"
mkdir -p "parte-14-permissoes-roles-rbac"
mkdir -p "parte-15-modulo-configuracao-personalizacao"
mkdir -p "parte-16-sistema-notificacoes-alertas"
mkdir -p "parte-17-email-marketing-automacao"
mkdir -p "parte-18-analytics-business-intelligence"
mkdir -p "parte-19-gestao-documentos-arquivos"
mkdir -p "parte-20-performance-otimizacao-cache"
mkdir -p "parte-21-seguranca-avancada-compliance"
mkdir -p "parte-22-backup-disaster-recovery"
mkdir -p "parte-23-logs-auditoria-compliance"
mkdir -p "parte-24-integracao-apis-externas"
mkdir -p "parte-25-gestao-usuarios-multi-tenant"
mkdir -p "parte-26-configuracao-whitelabel-branding"
mkdir -p "parte-27-comunicacao-colaboracao-interna"
mkdir -p "parte-28-mobile-pwa-otimizacao"
mkdir -p "parte-29-analytics-bi-dashboards-avancados"
mkdir -p "parte-30-ia-machine-learning-ollama"
mkdir -p "parte-31-automacao-workflows-n8n"
mkdir -p "parte-32-apis-integracoes-gateway"
mkdir -p "parte-33-analise-preditiva-ia"
mkdir -p "parte-34-recomendacoes-inteligentes-ai"
mkdir -p "parte-35-auto-scaling-ia-otimizacao"
mkdir -p "parte-36-evolution-api-whatsapp-config"
mkdir -p "parte-37-chatwoot-atendimento-omnichannel"
mkdir -p "parte-38-typebot-workflows-conversacionais"
mkdir -p "parte-39-n8n-automacao-avancada-ia"
mkdir -p "parte-40-mautic-marketing-automacao"
mkdir -p "parte-41-email-marketing-campanhas-ia"
mkdir -p "parte-42-sms-push-notifications-mobile"
mkdir -p "parte-43-social-media-integracoes"
mkdir -p "parte-44-crm-vendas-pipeline"
mkdir -p "parte-45-agendamento-inteligente-cobranca"
mkdir -p "parte-46-analise-comercial-inteligencia"
mkdir -p "parte-47-atendimento-ia-multimodal"
mkdir -p "parte-48-crm-funil-vendas-automacao"
mkdir -p "parte-49-portal-cliente-treinamento"
mkdir -p "parte-50-go-live-producao-final"

echo "✅ Todas as 50 pastas dos tutoriais foram criadas com sucesso!"
echo "🔧 Foco: Configurações externas das stacks Docker Swarm na rede Kryonix-NET"
echo "📱 Mobile-first para 80% dos usuários"
echo "🤖 IA 100% autônoma com dados reais"
echo "🇧🇷 Interface em português para leigos"
